name: Build and Deploy Develop

on:
  push:
    branches: [ develop ]

jobs:

  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: Install Dependencies
      run: npm install
      
    - name: Build
      env:
        NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_DEV_API_BASE_URL }}
        NEXT_PUBLIC_INFURA_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_DEV_INFURA_PROJECT_ID }}
        NEXT_PUBLIC_FORTMATIC_KEY: ${{ secrets.NEXT_PUBLIC_DEV_FORTMATIC_KEY }}
        NEXT_PUBLIC_ROPSTEN_HOSTNAME: ${{ secrets.NEXT_PUBLIC_ROPSTEN_HOSTNAME }}
      run: npm run build
   
    - name: Export
      run: npm run export
      
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ${{ secrets.DEV_FTP_SERVER }}
        username: ${{ secrets.DEV_FTP_USERNAME }}
        password: ${{ secrets.DEV_FTP_PASSWORD }}
        local-dir: ./out/
